### ISSUE TITLE
关于python版本的问题

### ISSUE THREAD

**Issue by pikaqiu-ru** [AnxiangLemon/MyIdaFrida#1]
请问下，使用的你的脚本，对于python版本和ida有什么要求吗？我的python版本是3.7.5，ida版本是ida7.6,无法在ida显示idafrida选项
![image](https://github.com/AnxiangLemon/MyIdaFrida/assets/22478023/74682813-0ad5-4682-80bd-590a2992e9a5)

**Comment by AnxiangLemon** [comment]
我的运行环境是idapro 7.7 python版本 3.8.10  也行是和其他插件有冲突
